version: '3'

services:
  # TODO: 配置服务器
  server:
    image: egg-chat
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 7001:7001
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js
  # TODO: 配置web
  web:
  # TODO: 配置mongodb
  mongodb: